id: AB8CEBBCC
title: Short Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:01:46.892317
  last_modified_at: 2022-03-01 00:01:46.892321
