id: AB8CEBBCC
title: Prayer to Jetsün Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:01:46.890421
  last_modified_at: 2022-03-01 00:01:46.890427
